### ISSUE TITLE
Periodic (streamed) updates of the sugestions 

### ISSUE THREAD

**Issue by wclr** [enquirer/prompt-autocompletion#2]
Is it difficult to make source not promise (single resolve) but stream-like, that would allow periodical update of the suggestions without user input?

**Comment by doowb** [comment]
This repository has been archived in favor of the new version of [Enquirer](https://github.com/enquirer/enquirer).

In there new version, we have [an example of streaming](https://github.com/enquirer/enquirer/blob/master/examples/autocomplete/option-suggest-streaming.js) using the autocomplete prompt. Please take a look at that and if you have any issues, feel free to open a new issue there.
